import { NextResponse } from "next/server";

import { MAX_BATCH, recordEvents, type IncomingEvent } from "@/lib/events";
import {
  glydeCorsHeaders,
  glydeCorsPreflight,
  isTrustedGlydeOrigin,
} from "@/lib/glyde-cors";

export const dynamic = "force-dynamic";
export const revalidate = 0;
export const runtime = "nodejs";

// Ingest for the first-party analytics beacon. The client sends batches, often
// through navigator.sendBeacon on page-hide, so this has to accept a request
// whose page is already gone: no cookies are read, nothing is returned that the
// client needs, and a failure is never surfaced to the visitor.

const MAX_BODY_BYTES = 32_768;
const ID_PATTERN = /^[A-Za-z0-9_-]{8,64}$/;

// Per-IP throttle. A page-hide beacon plus periodic flushes puts a normal
// session in single digits per minute; this leaves generous headroom while
// still capping a script pointed at the endpoint.
const WINDOW_MS = 60_000;
const MAX_REQUESTS_PER_WINDOW = 60;
const buckets = new Map<string, { count: number; resetAt: number }>();

function rateLimited(key: string): boolean {
  const now = Date.now();
  const bucket = buckets.get(key);

  if (!bucket || bucket.resetAt <= now) {
    buckets.set(key, { count: 1, resetAt: now + WINDOW_MS });

    if (buckets.size > 5_000) {
      for (const [candidate, value] of buckets) {
        if (value.resetAt <= now) buckets.delete(candidate);
      }
    }
    return false;
  }

  bucket.count += 1;
  return bucket.count > MAX_REQUESTS_PER_WINDOW;
}

function emptyResponse(request: Request, status: number) {
  return new NextResponse(null, {
    status,
    headers: {
      "Cache-Control": "no-store, max-age=0",
      ...glydeCorsHeaders(request),
    },
  });
}

function accepted(request: Request) {
  // 204 rather than a body: the sender is usually a beacon that cannot act on a
  // response, and an empty reply keeps the page-hide path cheap.
  return emptyResponse(request, 204);
}

export async function POST(request: Request) {
  if (!isTrustedGlydeOrigin(request)) {
    return emptyResponse(request, 403);
  }

  const forwarded = request.headers.get("x-forwarded-for");
  const key = forwarded?.split(",")[0]?.trim() || "unknown";

  if (rateLimited(key)) {
    return emptyResponse(request, 429);
  }

  const contentLength = Number(request.headers.get("content-length") ?? "0");
  if (Number.isFinite(contentLength) && contentLength > MAX_BODY_BYTES) {
    return emptyResponse(request, 413);
  }

  let payload: unknown;
  try {
    const text = await request.text();
    if (text.length > MAX_BODY_BYTES) {
      return emptyResponse(request, 413);
    }
    payload = JSON.parse(text);
  } catch {
    return emptyResponse(request, 400);
  }

  if (typeof payload !== "object" || payload === null) {
    return emptyResponse(request, 400);
  }

  const body = payload as {
    visitorId?: unknown;
    sessionId?: unknown;
    events?: unknown;
  };

  // The ids are generated by the client, so they are treated as untrusted input
  // and must look like the ids we issue before they become a grouping key.
  if (
    typeof body.visitorId !== "string" ||
    typeof body.sessionId !== "string" ||
    !ID_PATTERN.test(body.visitorId) ||
    !ID_PATTERN.test(body.sessionId) ||
    !Array.isArray(body.events) ||
    body.events.length === 0
  ) {
    return emptyResponse(request, 400);
  }

  const events = body.events
    .filter((event): event is IncomingEvent => typeof event === "object" && event !== null)
    .slice(0, MAX_BATCH);

  if (events.length === 0) {
    return emptyResponse(request, 400);
  }

  try {
    recordEvents(body.visitorId, body.sessionId, events);
  } catch (error) {
    // Losing analytics must never look like a broken page.
    console.error("[events] failed to record batch", error);
    return emptyResponse(request, 500);
  }

  return accepted(request);
}

export function OPTIONS(request: Request) {
  return glydeCorsPreflight(request);
}
